### ISSUE TITLE
AUR4 support

### ISSUE THREAD

**Issue by The-Compiler** [archlinuxfr/yaourt#115]
Hi!

I wanted to write down some idea(s) I had for AUR4 support.

Looking at the current state, it seems only AUR *or* AUR4 support is possible, right? I think it'd be awesome to have "hybrid" support for AUR4 and the old (readonly) AUR archive - what do you think?

The version number could be shown in red for packages in the old AUR (with a clear message), like for outdated packages.

Then it'd be easy to discover packages I'd like which are only in the old AUR, so I can adopt them.

**Comment by jristz** [comment]
Hybrid support need to land before july 8 and removed after july 8 since AUR4 will become AUR and AUR4 webpage will redirect to AUR.

**Comment by The-Compiler** [comment]
If I understand it correctly, the (old) AUR would still be available as a read-only archive after that - what I'm mainly interested in is support for that once the transition is complete.

This would help people to find old PKGBUILDs and (hopefully) adopt them.

**Comment by jristz** [comment]
As far I underestand that readonly will last only until august 8 when the
repo will be wipped out.

I think is better ask in the mailist, maye they could clarify what could
happend with the old aur and the packages.

better safer than sorrier.

2015-06-08 17:41 GMT-03:00 Florian Bruhin <notifications@github.com>:

> If I understand it correctly, the (old) AUR would still be available as a
> read-only archive after that - what I'm mainly interested in is support for
> that once the transition is complete.
>
> This would help people to find old PKGBUILDs and (hopefully) adopt them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxfr/yaourt/issues/115#issuecomment-110132348>.
>



-- 
*Pablo Lezaeta*

**Comment by The-Compiler** [comment]
From the annoucement mail:

> On August 8th, the archive at aur.archlinux.org will be replaced by
> aur4.archlinux.org and the former aur.archlinux.org source tarballs will be
> made available for reference.

So the data definitely will be *available* - the question is whether pkgquery/yaourt can deal with it easily though...

**Comment by wlritchi** [comment]
I'm not really sure trying to do this is a great idea. In theory, any package that's still maintained should appear on the new repo, and any package that's not maintained is best considered broken. Having an AUR helper that's also an archived-old-version-of-AUR helper seems like unexpected behaviour.

Specific problem: What happens if a package was renamed when it was migrated, for some reason? Suppose a user reads an old page mentioning the package and tries to install it. Without AUR archive support, it fails, and the user looks up the package and finds the current name. With support, they get an outdated copy of the package and possibly are unaware of this.

If you find yourself needing a package that's not in the new repo, the best course of action is probably to create it yourself. Either it's a straightforward run of a migration script and you've just helped everyone by verifying this and creating the new package, or it's too complicated for yaourt to have dealt with it anyway. To do anything else would, I think, just put us in legacy code hell.

What does yaourt currently do if a package that it installed no longer appears on the AUR?

**Comment by nengxu** [comment]
Is aur4 already supported by yaourt? I tried today. And it seems not yet. I'm using the 1.6-1 package from archlinuxfr repo. Please advice the status. Thanks.

**Comment by ArchangeGabriel** [comment]
With package-query 1.6.2 (released today), it does work (you have to add --aur-url https://aur4.archlinux.org in your commands).

**Comment by nengxu** [comment]
@ArchangeGabriel Yes, it works. Thanks.

**Comment by lopsided98** [comment]
Setting AURURL="https://aur4.archlinux.org" in /etc/yaourtrc also works.

**Comment by Manouchehri** [comment]
I did what @lopsided98 suggested, no issues. Works flawlessly.

**Comment by techwiz2100** [comment]
Just a thought, but wouldn't it be a good idea to add support for multiple AURURLs to support this, or something like this in the future and also support custom/personal repos. I think we could just grab the latest version of whatever package from each url in AURURL and show results from the most up to date or something.

**Comment by colemickens** [comment]
Is there a plan to push a build with AUR4 as the default, soon or shortly after July 8th?

**Comment by wlritchi** [comment]
AUR4 will become the default on August 8th when it moves to aur.archlinux.org. Until that time, you can set AURURL in your yaourtrc as described above.

**Comment by balkierode** [comment]
If I set AURURL to AUR4 in yaourtrc and install some packages today, will those packages updated automatically once I remove the setting on aug 8?

**Comment by warmwaffles** [comment]
> If I set AURURL to AUR4 in yaourtrc and install some packages today, will those packages updated automatically once I remove the setting on aug 8?

In theory yes. I assume they will change the sub domain to point at aur4 and everything should be good after that.

**Comment by Skunnyk** [comment]
Yes, AUR4 will be "migrated" back to aur.archlinux.org on August 8th ( and I think there will be a redirect 301 from aur4=>aur). 
So you'll only need to remove the AURURL custom settings at this moment.

**Comment by Skunnyk** [comment]
AUR4 is now live, and I think that it works :) 
Don't forget to remove aur4 AURURL  from your config, in case of deletion of aur4.archlinux.org subdomain.

**Comment by warmwaffles** [comment]
Heh, yes, I had this set as a calendar event to change the config.
