### ISSUE TITLE
yaourt does not respect PACMAN="powerpill"

### ISSUE THREAD

**Issue by txtsd** [archlinuxfr/yaourt#176]
`~/.config/yaourt/yaourtrc`

It respects other settings, but not this one. Packages are downloaded using `pacman`. At first I thought it was only dependencies of AUR packages, but it uses `pacman` for regular packages too.

I even tried `PACMAN="/usr/bin/powerpill"` but it still uses `pacman`.

My `powerpill` is configured to use `aria2c` to download packages, so the downloading output looks very different. `yaourt` shows the `pacman` output and the downloads are as slow as `pacman`'s downloads.

**Comment by larchunix** [comment]
According to my tests, `yaourt` honours correctly the `PACMAN` setting.

However, `powerpill` command line interface is not strictly compatible with `pacman`. For instance, with `powerpill` the following commands do not produce the same result:

    $ powerpill -S gtk3       => uses aria2c to download packages
    $ powerpill -S extra/gtk3 => uses pacman to download packages

Your problem occurs because `yaourt` executes `PACMAN` using the second form.

IMHO, this issue should be fixed on `powerpill`'s side.

**Comment by txtsd** [comment]
Thanks, I'll let the dev know.

**Comment by txtsd** [comment]
Powerpill dev confirmed and fixed the issue!
