### ISSUE TITLE
[feature request] show changes

### ISSUE THREAD

**Issue by mattia-b89** [archlinuxfr/yaourt#289]
add the ability to show the changes between package updates prior to upgrade them.
really useful when upgrading from a release to another
(i.e. the same feature in AUR web)

**Comment by ArchangeGabriel** [comment]
The is currently the AURSHOWDIFF option that works together with AURUSEGIT, but there are several flaws:

– missing commit messages ;
– not working if the installed version doesn’t match one in AUR (e.g. for -git package).

OTOH, I like to have a diff between now and what I have rather than the full commit log.

**Comment by ArchangeGabriel** [comment]
And I might add that a diff without using git would be nice, but I’m not sure whether AUR RPC interface provides this.
