### ISSUE TITLE
makepkg 4.2.0 broke "--asroot" parameter

### ISSUE THREAD

**Issue by notuxic** [archlinuxfr/yaourt#67]
With the update of makepkg to version 4.2.0 the "--asroot" parameter isn't available anymore.
Thus, when trying to build the error ``makepkg: invalid option '--asroot' `` is raised.
This could be solved by creating a user "yaourt" and executing makepkg with sudo using this user.

Changes in makepkg for version 4.2.0:
https://projects.archlinux.org/pacman.git/tree/NEWS#n54

**Comment by Skunnyk** [comment]
Hm, yep, maybe a solution. 
Packer try to implement the same behavior : https://github.com/keenerd/packer/issues/131#issuecomment-68500946 , with a "pacman" user (but it would be better in the .install step instead of adding user on-the-fly on runtime imo).
Waiting for @tuxce advise :)

**Comment by DepthDeluxe** [comment]
Removing the `--asroot` option also appears to have broken GNU Puppet.  It uses the option to run `makepkg` on AUR packages.

**Comment by evert-mouw** [comment]
# Dirty solution for the makepkg asroot problem

**Background**: The maintainers of the `makepkg` utility used to create Arch packages have, in all their infinite wisdom to protect the lesser beings, removed the `asroot` option and the possibility to build packages as user root.

**My take**: Arch started out great because it worked like Slackware: KISS and the ability to shoot yourself in the foot.

## Temporary, somewhat ugly fix

We can edit `/usr/bin/makepkg` of course :-)

Add `asroot` to `OPT_LONG` (line 3366). Just search for "OPT_LONG".

	OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'force' 'geninteg'
			  'help' 'holdver' 'ignorearch' 'install' 'key:' 'log' 'noarchive' 'nobuild'
			  'nocolor' 'nocheck' 'nodeps' 'noextract' 'noprepare' 'nosign' 'pkg:' 'repackage'
			  'rmdeps' 'sign' 'skipchecksums' 'skipinteg' 'skippgpcheck' 'source' 'syncdeps'
			  'verifysource' 'version' 'asroot')

Remove EUID check (line 3577). Just search for "EUID".

	if (( ! INFAKEROOT )); then
		if (( EUID == 0 )); then
			#error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
	#catastrophic damage to your system.")" "makepkg"
			#exit 1 # $E_USER_ABORT
			plain "$(gettext "Running as root restored by Orc ;)")"
		fi

## Make it permanent

Maybe don't do that. You could consider creating a patch file and applying the patch before running tools such as yaourt, packer or apacman. But soon enough those tools will very likely install a user on your system and let that user run makepkg.

**Comment by tuxce** [comment]
I'm not in favor of yaourt creating or using a different user for makepkg.
How about let the user choose what to do ? 
Maybe someone pushed or will push  a 'makepkg_root' to AUR and with this commit 1997977af83b3681e81dadbb0247ef82ab6ce1ca he will be able to configure yaourt to use the new executable.

**Comment by balle** [comment]
Well I cannot use yaourt as before, because its not possible to use it in Puppet when it's prompting for a password dozen of times, but with the "somewhat ugly fix" above it's working again ;)
Ah and before I forget: Rule number one for every programmer is (or at least should be) dont remove a feature or users will hate you!

**Comment by dalu** [comment]
who is responsible for this?

**Comment by dalu** [comment]
https://gist.github.com/dalu/6cdda7e0376f602f97de

**Comment by l3iggs** [comment]
The removal of `--asroot` has broken all of my arch docker images (inside which only the root user exists).

Please bring back `--asroot` exactly as it was as soon as possible and let me decide for myself what is dangerous and what is not on my systems.

**Comment by l3iggs** [comment]
I've sent an email requesting the reinstatement of --asroot to pacman-dev@archlinux.org

**Comment by bts368** [comment]
@l3iggs 
I haven't checked the list archives yet, but I highly doubt you'll get anywhere productive. See the issue I filed, https://bugs.archlinux.org/task/43302
It was closed as WONTFIX. 

I do want to take the time now to stress that this breakage is *not* the archlinux-fr team's fault. It is the pacman devs (and, as @evert-mouw pointed out, their straying from the Arch Way(TM).)

**Comment by evert-mouw** [comment]
@bts368 Thanks for your issue. It is unfortunate that the devs don't give it much consideration. Well. I guess that's why I use Scientific Linux or Ubuntu for my home server virtual machines. Package management is too important to let it be influenced by amateurish devs. (Maybe the original Slackware philosophy also has merit: Try to avoid such "management" in the first place. But I cannot live without dependency resolving.)

I still love arch but this isn't the right way. Sorry for my slightly offtopic rant. I agree that the archlinux-fr team is doing a great job. As I only use Arch on one of my desktop machines, this whole issue doesn't hurt me much, but I really don't like the whole "we protect the stupid user from his own actions" mentality that seems to gain ground.

**Comment by bts368** [comment]
I just updated the upstream issue (#43302), as ironically, the Arch Way I quoted is *supported by phrakture himself* (for those unaware, phrakture is the lead developer).

I've requested re-open. If it gets closed as WONTFIX again, I have no idea where to take it to next, but we aren't the only ones complaining about this.

**Comment by bts368** [comment]
https://bugs.archlinux.org/task/43302
okay. so looks like we're on our own. apparently "competent linux user" = "fork it if we break the way you use it"

like ubuntu.

that said, the faster we find a workaround, the better IMO. @tuxce, up for a bugjam? it should be a pretty quick one, but i need some help walking around the functions library.

**Comment by bts368** [comment]
if someone's feeling brave/has extra time on their hands, can you clone, make, package, and install from my fork at https://github.com/bts368/yaourt  to see if it installs and works as expected?

("as expected" means "you should be able to run yaourt as root with no warnings received and a successfully installed package")

**Comment by tuxce** [comment]
Like I writed in my last comment, yaourt-git can be configured to change the makepkg executable : 1997977af83b3681e81dadbb0247ef82ab6ce1ca
Anyone can use @dalu patch  (https://gist.github.com/dalu/6cdda7e0376f602f97de) to push a PKGBUILD and have a makepkg with different name that execute as root.
And use something like : 

    MAKEPKG='makepkg_replacement' yaourt <...>

or by setting MAKEPKG in yaourtrc.

**Comment by bts368** [comment]
whoops! i must have missed that; terribly sorry, @tuxce.

i'll just submit a PR for the man page then.

when do you plan on updating the stable yaourt?

**Comment by quentindemetz** [comment]
https://github.com/archlinuxfr/yaourt/issues/67#issuecomment-68626199 fixed it for me, but for how long?

**Comment by fabiofalci** [comment]
oh man, all my docker images are broken now
